language: ruby
script:
  - bundle exec rake spec
rvm:
  - 1.8.7
  - ree
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - rbx-18mode
  - rbx-19mode
  - jruby
  - jruby-18mode
matrix:
  allow_failures:
    - rvm: ruby-head
